-- =====================================================================
-- JY STUDIO — Supabase 초기 설정 SQL  (v2)
-- 사용법: Supabase 대시보드 → SQL Editor → 아래 전체 붙여넣고 RUN
--        (여러 번 실행해도 안전하도록 작성되어 있습니다)
-- =====================================================================

-- 1) 포트폴리오 테이블 -------------------------------------------------
create table if not exists public.portfolio (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  sort_order  int         not null default 0,
  category    text,
  title       text        not null,
  media_type  text        not null default 'youtube',  -- youtube | video | image
  media       text,                                    -- youtube 영상 ID 또는 파일 URL
  description text
);

-- 2) 공지사항 테이블 ---------------------------------------------------
create table if not exists public.notices (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  date        text,
  title       text        not null,
  body        text
);

-- 3) 실시간 문의(채팅) 테이블 -------------------------------------------
create table if not exists public.chat_sessions (
  id              uuid primary key default gen_random_uuid(),
  created_at      timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  name            text,
  email           text,
  source          text not null default 'chat',   -- chat(위젯) | form(문의폼)
  status          text not null default 'open'    -- open | closed
);

create table if not exists public.chat_messages (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  session_id    uuid not null references public.chat_sessions(id) on delete cascade,
  sender        text not null check (sender in ('visitor','admin')),
  body          text not null,
  read_by_admin boolean not null default false
);
create index if not exists chat_messages_session_idx on public.chat_messages(session_id, created_at);
create index if not exists chat_sessions_last_idx    on public.chat_sessions(last_message_at desc);

-- 4) 방문자 통계 테이블 --------------------------------------------------
create table if not exists public.visits (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  visitor_id text,          -- 브라우저별 익명 ID (localStorage)
  is_new     boolean default true,
  path       text,
  referrer   text,
  country    text,
  region     text,
  city       text,
  device     text,          -- mobile | tablet | desktop
  lang       text,
  ua         text
);
create index if not exists visits_created_idx on public.visits(created_at desc);

-- 5) 외주 공고함 테이블 (자동 수집 스크립트가 채움) -----------------------
create table if not exists public.job_leads (
  id         bigint generated by default as identity primary key,
  fetched_at timestamptz not null default now(),
  source     text not null,          -- wishket | freemoa | ...
  title      text not null,
  url        text not null unique,
  budget     text,
  posted     text,
  extra      text,
  keywords   text[],
  is_read    boolean not null default false
);
create index if not exists job_leads_fetched_idx on public.job_leads(fetched_at desc);

-- 6) RLS(행 수준 보안) 켜기 ----------------------------------------------
alter table public.portfolio     enable row level security;
alter table public.notices       enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.visits        enable row level security;
alter table public.job_leads     enable row level security;

-- 7) 정책 ------------------------------------------------------------------
-- portfolio: 누구나 읽기(사이트 노출), 로그인한 관리자만 쓰기
drop policy if exists "portfolio_read"  on public.portfolio;
drop policy if exists "portfolio_write" on public.portfolio;
create policy "portfolio_read"  on public.portfolio for select to anon, authenticated using (true);
create policy "portfolio_write" on public.portfolio for all    to authenticated using (true) with check (true);

-- notices: 누구나 읽기, 관리자만 쓰기
drop policy if exists "notices_read"  on public.notices;
drop policy if exists "notices_write" on public.notices;
create policy "notices_read"  on public.notices for select to anon, authenticated using (true);
create policy "notices_write" on public.notices for all to authenticated using (true) with check (true);

-- 채팅/방문/공고: 관리자(authenticated)만 직접 접근.
-- 방문자는 아래 8)의 RPC 함수를 통해서만 제한적으로 쓰기/읽기 가능.
drop policy if exists "chat_sessions_admin" on public.chat_sessions;
create policy "chat_sessions_admin" on public.chat_sessions for all to authenticated using (true) with check (true);

drop policy if exists "chat_messages_admin" on public.chat_messages;
create policy "chat_messages_admin" on public.chat_messages for all to authenticated using (true) with check (true);

drop policy if exists "visits_admin" on public.visits;
create policy "visits_admin" on public.visits for select to authenticated using (true);

drop policy if exists "job_leads_admin" on public.job_leads;
create policy "job_leads_admin" on public.job_leads for all to authenticated using (true) with check (true);

-- 8) 방문자용 RPC 함수 (security definer: RLS를 우회하되 딱 필요한 일만 함) --

-- 8-1) 채팅 메시지 보내기 (세션이 없으면 자동 생성)
create or replace function public.chat_send(
  p_session uuid,
  p_body    text,
  p_name    text default null,
  p_email   text default null,
  p_source  text default 'chat'
) returns void
language plpgsql security definer set search_path = public as $$
begin
  if p_session is null then raise exception 'session required'; end if;
  if p_body is null or length(trim(p_body)) = 0 then raise exception 'empty message'; end if;
  if length(p_body) > 4000 then raise exception 'message too long'; end if;

  insert into chat_sessions (id, name, email, source, last_message_at)
  values (
    p_session,
    nullif(left(trim(coalesce(p_name ,'')),  80), ''),
    nullif(left(trim(coalesce(p_email,'')), 120), ''),
    case when p_source = 'form' then 'form' else 'chat' end,
    now()
  )
  on conflict (id) do update set
    last_message_at = now(),
    status = 'open',
    name  = coalesce(excluded.name , chat_sessions.name),
    email = coalesce(excluded.email, chat_sessions.email);

  insert into chat_messages (session_id, sender, body)
  values (p_session, 'visitor', trim(p_body));
end $$;

-- 8-2) 자기 세션의 대화 내역 불러오기 (세션 UUID를 아는 사람만)
create or replace function public.chat_history(p_session uuid)
returns table (id bigint, created_at timestamptz, sender text, body text)
language sql security definer set search_path = public as $$
  select m.id, m.created_at, m.sender, m.body
  from chat_messages m
  where m.session_id = p_session
  order by m.created_at asc
  limit 500;
$$;

-- 8-3) 방문 기록 남기기
create or replace function public.record_visit(
  p_visitor  text default null,
  p_is_new   boolean default true,
  p_path     text default null,
  p_referrer text default null,
  p_country  text default null,
  p_region   text default null,
  p_city     text default null,
  p_device   text default null,
  p_lang     text default null,
  p_ua       text default null
) returns void
language plpgsql security definer set search_path = public as $$
begin
  insert into visits (visitor_id, is_new, path, referrer, country, region, city, device, lang, ua)
  values (
    left(coalesce(p_visitor,''), 64),
    coalesce(p_is_new, true),
    left(coalesce(p_path,''), 200),
    left(coalesce(p_referrer,''), 300),
    left(coalesce(p_country,''), 80),
    left(coalesce(p_region,''), 80),
    left(coalesce(p_city,''), 80),
    left(coalesce(p_device,''), 20),
    left(coalesce(p_lang,''), 20),
    left(coalesce(p_ua,''), 300)
  );
end $$;

grant execute on function public.chat_send(uuid, text, text, text, text) to anon, authenticated;
grant execute on function public.chat_history(uuid)                      to anon, authenticated;
grant execute on function public.record_visit(text, boolean, text, text, text, text, text, text, text, text) to anon, authenticated;

-- 9) 실시간(Realtime) 알림 켜기 — 관리자 앱이 새 메시지를 즉시 받도록 -----
do $$ begin
  alter publication supabase_realtime add table public.chat_messages;
exception when duplicate_object then null; end $$;

-- 10) 미디어 저장소(Storage) — 포트폴리오 이미지/영상 업로드용 --------------
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

drop policy if exists "media_public_read"  on storage.objects;
drop policy if exists "media_admin_insert" on storage.objects;
drop policy if exists "media_admin_update" on storage.objects;
drop policy if exists "media_admin_delete" on storage.objects;
create policy "media_public_read"  on storage.objects for select to anon, authenticated using (bucket_id = 'media');
create policy "media_admin_insert" on storage.objects for insert to authenticated with check (bucket_id = 'media');
create policy "media_admin_update" on storage.objects for update to authenticated using (bucket_id = 'media');
create policy "media_admin_delete" on storage.objects for delete to authenticated using (bucket_id = 'media');

-- 11) (선택) 시작용 예시 데이터 -------------------------------------------
insert into public.notices (date, title, body)
select '2026.07.24', '홈페이지 새단장 & 포트폴리오 업데이트 안내',
       '안녕하세요, JY 스튜디오입니다. 홈페이지를 새롭게 단장했습니다. 방문해 주셔서 감사합니다.'
where not exists (select 1 from public.notices);

insert into public.portfolio (sort_order, category, title, media_type, media)
select * from (values
  (1, 'Spine 2D', 'Animation Reel',   'youtube', '8Pqw7y6g3L8'),
  (2, 'Spine 2D', 'Character Motion', 'youtube', 'OxhRAaGaMrw')
) as v(sort_order, category, title, media_type, media)
where not exists (select 1 from public.portfolio);

-- =====================================================================
-- 완료! 다음 단계:
--  1. Authentication → Users 에서 관리자 계정을 1개 추가 (Add user)
--  2. Authentication → Sign In / Up → Email 에서
--     "Allow new users to sign up" 을 반드시 꺼두세요 (관리자 외 가입 차단)
--  3. supabase-config.js 에 Project URL 과 anon key 를 입력
-- =====================================================================
