-- =====================================================================
-- JY STUDIO — 업데이트 1: 포트폴리오 전체 이전 + 대표작 구분 + 팀 경력
-- 사용법: Supabase 대시보드 → SQL Editor → 전체 붙여넣고 RUN
-- ⚠️ 주의: portfolio 테이블을 홈페이지의 34개 작업물로 새로 채웁니다.
--          (관리자 앱에서 직접 추가한 작업물이 있다면 실행 전에 백업하세요)
-- =====================================================================

-- 1) 대표 포트폴리오 구분 컬럼 -------------------------------------------
alter table public.portfolio add column if not exists featured boolean not null default false;

-- 2) 팀 경력 테이블 -------------------------------------------------------
create table if not exists public.team_members (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  sort_order int  not null default 0,
  name       text not null,
  role       text,
  careers    text          -- 경력 사항, 한 줄에 하나씩
);
alter table public.team_members enable row level security;
drop policy if exists "team_read"  on public.team_members;
drop policy if exists "team_write" on public.team_members;
create policy "team_read"  on public.team_members for select to anon, authenticated using (true);
create policy "team_write" on public.team_members for all to authenticated using (true) with check (true);

-- 2-1) 직원 관리 테이블 (관리자 전용 — 사이트에 노출되지 않음) --------------
create table if not exists public.employees (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  sort_order int  not null default 0,
  name       text not null,
  position   text,          -- 직급
  phone      text,          -- 전화번호
  bank       text,          -- 은행명
  account    text,          -- 계좌번호
  hired_on   date           -- 입사일
);
alter table public.employees enable row level security;
drop policy if exists "employees_admin" on public.employees;
create policy "employees_admin" on public.employees for all to authenticated using (true) with check (true);
-- (anon 정책 없음 = 로그인한 관리자만 접근 가능)

-- 3) 포트폴리오 데이터 전체 교체 (홈페이지 하드코딩 → DB) ------------------
delete from public.portfolio;
insert into public.portfolio (sort_order, category, title, media_type, media, description, featured) values
  ( 1, 'Spine 2D',       'Animation Reel',        'youtube', '8Pqw7y6g3L8', '스파인 2D 애니메이션 작업', true),
  ( 2, 'Spine 2D',       'Character Motion',      'youtube', 'OxhRAaGaMrw', '캐릭터 모션 작업', true),
  ( 3, 'Game Character', 'Frostline Operative',   'video',   'char1.mp4',   '전투 캐릭터 리깅 & 모션', false),
  ( 4, 'Game Character', 'Holo Idol',             'video',   'char2.mp4',   '아이돌 캐릭터 리깅 & 모션', false),
  ( 5, 'Spine 2D',       'Showreel 01',           'youtube', 'fe4p8mnmSD4', '애니메이션 작업 영상', false),
  ( 6, 'Spine 2D',       'Showreel 02',           'youtube', 'ONyb_c_zGpA', '애니메이션 작업 영상', false),
  ( 7, 'Spine 2D',       'Showreel 03',           'youtube', '36kXUbnpzdU', '애니메이션 작업 영상', false),
  ( 8, 'Animation',      'Motion Clip 01',        'video',   'https://embed.notion.co/files/3537d5da098f9cb144d9dd2810238a90.mp4', '애니메이션 작업물', false),
  ( 9, 'Animation',      'Motion Clip 02',        'video',   'https://embed.notion.co/files/289027deb063742c70d057c0290925aa.mp4', '애니메이션 작업물', false),
  (10, 'Animation',      'Motion Clip 03',        'video',   'https://embed.notion.co/files/cc88eed0674c60117d97030def1c3f45.mp4', '애니메이션 작업물', false),
  (11, 'Animation',      'Motion Clip 04',        'video',   'https://embed.notion.co/files/e75fbe469842b5d60a4996fd802b453d.mp4', '애니메이션 작업물', false),
  (12, 'Animation',      'Motion Clip 05',        'video',   'https://embed.notion.co/files/1586aba7c1a1d25141a1413441540164.mp4', '애니메이션 작업물', false),
  (13, 'Idle',           'Twin Blade — Idle',     'video',   'p1.mp4',  '쌍검 캐릭터 대기 모션', false),
  (14, 'Attack',         'Twin Blade — Slash',    'video',   'p2.mp4',  '쌍검 공격 모션', false),
  (15, 'Idle',           'Dagger Rogue — Idle',   'video',   'p4.mp4',  '단검 캐릭터 대기 모션', false),
  (16, 'Attack',         'Dagger Rogue — Stance', 'video',   'p5.mp4',  '단검 전투 자세 모션', false),
  (17, 'Attack',         'Dagger Rogue — Combo',  'video',   'p6.mp4',  '단검 연속 공격 모션', false),
  (18, 'Attack',         'Dagger Rogue — Leap',   'video',   'p7.mp4',  '단검 도약 공격 모션', false),
  (19, 'Idle',           'Dagger Rogue — Ready',  'video',   'p8.mp4',  '단검 전투 대기 모션', false),
  (20, 'Idle',           'Bunny Maul — Idle',     'video',   'p9.mp4',  '버니 망치 캐릭터 대기 모션', false),
  (21, 'Skill',          'Bunny Maul — Swing',    'video',   'p10.mp4', '망치 스윙 스킬 모션', false),
  (22, 'Skill',          'Bunny Maul — Smash',    'video',   'p11.mp4', '망치 내려치기 스킬 모션', false),
  (23, 'Attack',         'Bunny Maul — Spin',     'video',   'p12.mp4', '망치 회전 공격 모션', false),
  (24, 'Attack',         'Bunny Maul — Guard',    'video',   'p13.mp4', '망치 가드 모션', false),
  (25, 'Attack',         'Bunny Maul — Strike',   'video',   'p14.mp4', '망치 타격 모션', false),
  (26, 'Idle',           'Holly Dragon — Idle',   'video',   'p15.mp4', '크리스마스 드래곤 대기 모션', false),
  (27, 'Skill',          'Holly Dragon — Kick',   'video',   'p16.mp4', '드래곤 발차기 스킬 모션', false),
  (28, 'Attack',         'Holly Dragon — Combo',  'video',   'p17.mp4', '드래곤 연속 공격 모션', false),
  (29, 'Down',           'Holly Dragon — Down',   'video',   'p18.mp4', '드래곤 다운 모션', false),
  (30, 'Hit',            'Holly Dragon — Hit',    'video',   'p19.mp4', '드래곤 피격 모션', false),
  (31, 'Attack',         'Holly Dragon — Strike', 'video',   'p20.mp4', '드래곤 타격 모션', false),
  (32, 'Idle',           'Holly Dragon — Stance', 'video',   'p21.mp4', '드래곤 전투 자세 모션', false),
  (33, 'Emote',          'Chibi Emoticon',        'video',   'p22.mp4', '치비 이모티콘 애니메이션', false),
  (34, 'Rigging Detail', 'Arm Mesh Deform',       'video',   'p3.mp4',  '팔 메시 디포메이션 디테일', false);

-- 4) 팀 경력 데이터 (홈페이지 하드코딩 → DB) -------------------------------
delete from public.team_members;
insert into public.team_members (sort_order, name, role, careers) values
  ( 1, 'LEE EUN HYE',    'Senior 2D Animator', E'홍익대학교 조형대학 애니메이션\n<캣독런> 아트 (UI 제외 전반)\n인디팀 코코아게임즈 AD\n시나몬 게임즈 Spine 2D 애니메이터\n앤유 Spine 2D 애니메이터\n네오위즈 Spine 2D 애니메이터\n에픽세븐 Spine 2D 애니메이터'),
  ( 2, 'LEE SO HEE',     'Senior 2D Animator', E'애프터타임 Spine 2D 애니메이터\n노바코어 Spine 2D 애니메이터\n캐논크래커 Spine 2D 애니메이터\n마프게임즈 원화 및 Spine 2D 외주'),
  ( 3, 'LEE DONG YOUNG', 'Senior 2D Animator', E'한서항공전문대학교 항공기체정비과\n믹스포션 ''별의 여행자 라라'' 기획\nJY 스튜디오 Project Manager'),
  ( 4, 'JEON SU BIN',    '2D Art Designer',    E'상명대학교 컴퓨터과학과 / 미디어 아트\n경기콘텐츠진흥원 경기게임 아카데미 16기\n디패스트 임팩트 아트\n스튜디오 묘 공동대표'),
  ( 5, 'PARK TAE HYUONG','Senior 2D Animator', E'시프트업 ''승리의 여신: 니케'' 2D 애니메이터\n믹스포션 ''별의 여행자 라라'' 2D 애니메이터\nPUBG Studio ''Project KIZNA'' 2D 애니메이터\n스튜디오 묘 2D 애니메이터\nLuminaryTech Limited 2D 애니메이션 제작 총괄\n네오 아카데미 협업 강사'),
  ( 6, 'RYU JI MIN',     'Spine 2D Animator',  E'동서울대학교 게임컨텐츠과\nJY 스튜디오 Spine 2D 애니메이터'),
  ( 7, 'BAE GI MIN',     '2D Art Designer',    E'가천대학교 시각디자인학과\nKBS 드라마센터 무대연출\n바람의나라 게임풍 관리자\nCJ 홈쇼핑 연출\n경기도 새마크 디자이너\n스튜디오 묘 ''디패스트 임팩트'' 총괄'),
  ( 8, 'CHOI YOUNG EUN', 'Spine 2D Animator',  E'스카이피플 Spine 2D 애니메이터\n스튜디오비사이드 Spine 2D 애니메이터\n에피드게임즈 Spine 2D 애니메이터\nPUBG Spine 2D 애니메이터'),
  ( 9, 'KIM MI RA',      '2D Art Designer',    E'건국대학교 사회과학대학 융합인재학과\n엔퓨전 캐릭터 및 배경 아트 제작'),
  (10, 'AN CHAE WON',    '2D Artist',          E'울산애니고 애니과\n서울 호서대학교 게임그래픽과'),
  (11, 'CHEON YE WON',   '2D Artist',          E'인덕대학교 웹툰만화학과'),
  (12, 'KIM EUN JI',     'Spine 2D Animator',  E'청강문화산업대학교 패션디자인 전공\n불혹 소프트 아트 (UI, 배경 제외)\nI&V Games Spine 2D 애니메이터\n스노우 파이프 Spine 2D 애니메이터\n이모티브 Spine 2D 애니메이터\n스카이워크 Spine 2D 애니메이터'),
  (13, 'KIM YE WON',     'Spine 2D Animator',  E'경민대학교 게임콘텐츠과\n더재미 2D 디자이너\n크라운드터틀 Spine 2D 애니메이터\n프리티비지 Spine 2D 애니메이터\n클로버게임즈 Spine 2D 애니메이터');

-- 완료! 홈페이지와 관리자 앱을 새로고침하면 반영됩니다.
