-- =====================================================================
-- JY STUDIO — 업데이트 3: 직원 급여 항목 + 월별 근무 평가 (10점 만점)
-- 사용법: Supabase 대시보드 → SQL Editor → 전체 붙여넣고 RUN
-- =====================================================================

-- 1) 직원 테이블에 급여 항목 추가
alter table public.employees add column if not exists base_salary   numeric;  -- 기본급여(월, 원)
alter table public.employees add column if not exists overtime_rate numeric;  -- 초과근무 수당(시간당, 원)

-- 2) 월별 근무 평가 테이블 (직원별 · 월별 1개, 10점 만점)
create table if not exists public.employee_reviews (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  employee_id bigint not null references public.employees(id) on delete cascade,
  month       text not null,                                   -- 'YYYY-MM'
  score       int  not null check (score between 0 and 10),    -- 10점 만점
  note        text,
  unique (employee_id, month)
);

alter table public.employee_reviews enable row level security;
drop policy if exists "employee_reviews_admin" on public.employee_reviews;
create policy "employee_reviews_admin" on public.employee_reviews for all to authenticated using (true) with check (true);
-- (anon 정책 없음 = 로그인한 관리자만 접근)

-- 완료!
