-- =====================================================================
-- JY STUDIO — 업데이트 4: 계약서 보관함 (비공개 파일 저장소)
-- 사용법: Supabase 대시보드 → SQL Editor → 전체 붙여넣고 RUN
-- =====================================================================

-- 1) 계약서 목록 테이블 (파일 원본 이름·크기 기록)
create table if not exists public.contracts (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name       text not null,   -- 원본 파일명 (예: 니케_계약서.pdf)
  path       text not null,   -- 저장소 내부 경로
  size       bigint
);
alter table public.contracts enable row level security;
drop policy if exists "contracts_admin" on public.contracts;
create policy "contracts_admin" on public.contracts for all to authenticated using (true) with check (true);
-- (anon 정책 없음 = 관리자만 접근)

-- 2) 비공개 저장소 버킷 (public 아님! 서명된 링크로만 다운로드 가능)
insert into storage.buckets (id, name, public)
values ('docs', 'docs', false)
on conflict (id) do nothing;

drop policy if exists "docs_admin_select" on storage.objects;
drop policy if exists "docs_admin_insert" on storage.objects;
drop policy if exists "docs_admin_update" on storage.objects;
drop policy if exists "docs_admin_delete" on storage.objects;
create policy "docs_admin_select" on storage.objects for select to authenticated using (bucket_id = 'docs');
create policy "docs_admin_insert" on storage.objects for insert to authenticated with check (bucket_id = 'docs');
create policy "docs_admin_update" on storage.objects for update to authenticated using (bucket_id = 'docs');
create policy "docs_admin_delete" on storage.objects for delete to authenticated using (bucket_id = 'docs');

-- 완료!
