-- =====================================================================
-- JY STUDIO — 업데이트 5: 홈페이지 서비스 항목 관리
-- 사용법: Supabase 대시보드 → SQL Editor → 전체 붙여넣고 RUN
-- =====================================================================

create table if not exists public.services (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  sort_order  int  not null default 0,
  badge       text,            -- 카드 위 짧은 라벨 (예: RIG)
  title       text not null,   -- 영문 제목 (예: Character Rigging)
  subtitle    text,            -- 한글 부제 (예: 캐릭터 리깅 / 본 셋업)
  description text             -- 설명
);
alter table public.services enable row level security;
drop policy if exists "services_read"  on public.services;
drop policy if exists "services_write" on public.services;
create policy "services_read"  on public.services for select to anon, authenticated using (true);
create policy "services_write" on public.services for all to authenticated using (true) with check (true);

-- 현재 홈페이지 내용 그대로 이전
delete from public.services;
insert into public.services (sort_order, badge, title, subtitle, description) values
  (1, 'RIG', 'Character Rigging', '캐릭터 리깅 / 본 셋업',
   '일러스트를 본·메시 구조로 분해하고, 게임 엔진에서 바로 쓸 수 있는 깔끔한 스켈레톤을 설계합니다.'),
  (2, 'ANI', 'Animation Loops', '인게임 애니메이션 / 루프',
   'Idle, Walk, Attack, Skill — 캐릭터의 성격이 드러나는 모션을 프레임 단위로 다듬습니다.'),
  (3, 'FX', 'Cutscene & FX', '컷신 / 연출 / 이펙트',
   '스토리 컷신, 스킬 연출, UI 모션까지. 메시 디포메이션으로 입체감 있는 장면을 만듭니다.');

-- 완료!
