-- =====================================================================
-- JY STUDIO — 업데이트 6: 계정 로그인 이력 (모든 기기)
-- 사용법: Supabase 대시보드 → SQL Editor → 전체 붙여넣고 RUN
-- =====================================================================

create table if not exists public.login_history (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email      text,
  kind       text not null default 'login',   -- login=직접 로그인 | auto=자동 접속
  device     text,                             -- desktop/mobile · 앱/웹
  city       text,
  country    text,
  ua         text
);
create index if not exists login_history_time_idx on public.login_history(created_at desc);

alter table public.login_history enable row level security;
drop policy if exists "login_history_admin" on public.login_history;
create policy "login_history_admin" on public.login_history for all to authenticated using (true) with check (true);
-- (anon 정책 없음 = 관리자만 접근)

-- 완료!
