-- =====================================================================
-- JY STUDIO — 업데이트 2: 회계 장부 (외주비 정산 · 미수금 관리)
-- 사용법: Supabase 대시보드 → SQL Editor → 전체 붙여넣고 RUN
-- =====================================================================

create table if not exists public.ledger (
  id         bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  entry_date date not null default current_date,   -- 거래 날짜
  client     text,                                  -- 업체명
  title      text,                                  -- 내용 (예: 니케 캐릭터 3종 리깅)
  type       text not null default 'income' check (type in ('income','expense')),  -- income=수입(입금) | expense=지출(외주비)
  amount     numeric not null default 0,            -- 금액(원)
  status     text not null default 'unpaid' check (status in ('paid','unpaid')),   -- paid=정산완료 | unpaid=미정산(미수금/미지급)
  memo       text
);
create index if not exists ledger_date_idx on public.ledger(entry_date desc);

alter table public.ledger enable row level security;
drop policy if exists "ledger_admin" on public.ledger;
create policy "ledger_admin" on public.ledger for all to authenticated using (true) with check (true);
-- (anon 정책 없음 = 로그인한 관리자만 접근, 사이트에 노출되지 않음)

-- 완료!
